src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration = null;

    #[ORM\Column(length: 255)]
    private ?string $subtitle = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

        /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $Date;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?Category $Category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Get the value of Date
     */ 
    public function getDate()
    {
        return $this->Date;
    }

    /**
     * Set the value of Date
     *
     * @return  self
     */ 
    public function setDate($Date)
    {
        $this->Date = $Date;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }
}

templates/PDF/index.html.twig
<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Billet JO 2024</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .ticket-container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            border: 1px solid #ddd;
            background: #FFF;
        }
        .ticket-header,
        .footer-instructions {
            text-align: center;
            margin-bottom: 30px;
        }
        .footer-instructions {
            background-color: #EFEFEF;
            padding: 10px;
            font-size: 14px;
            margin-top: 30px;
            margin-bottom: 0; /* Remove extra spacing at the bottom */
        }
        .qr-code {
            text-align: center;
            margin: 20px 0;
        }
    </style>
</head>
<body>

<div class="ticket-container">
    <div class="ticket-header">
        {# <img src="{{ asset('path_to_olympic_logo.png') }}" alt="Logo JO 2024" style="max-width:100px;"> <!-- Inline styling for the logo size --> #}
        {# <img src="{{asset('assets/img/jo2024.png')}}" alt="Logo JO 2024" style="max-width:100px; "> #}

    </div>

    {% for item in ticket %}
    <div class="ticket-body">
        <div class="ticket-info">
            <p><strong>Sport:</strong> {{ item.sport }}</p>
            <p><strong>Type:</strong> {{ item.type }}</p>
            <p><strong>Date:</strong> {{ item.date|date('d-m-Y H:i') }}</p>
        </div>
        <div class="qr-code">
            <img src="{{ qrcode }}" alt="QR Code">
        </div>
    </div>
    {% endfor %}

<div class="footer-instructions">
    <p>Accédez à l’événement JO2024 en présentant ce billet unique aux contrôles et veillez à l’accompagnement de tous les spectateurs simultanément.</p>
    <p>La reproduction non autorisée de ce billet est interdite et soumise à des conséquences légales; tout duplicata peut entraîner un refus d’entrée sans remboursement.</p>
</div>

</div>

</body>
</html>